CREATE DATABASE happiness;
USE happiness;

CREATE TABLE `cities` (
id INTEGER NOT NULL PRIMARY KEY, 
city VARCHAR(50) NOT NULL,
life_quality DECIMAL(5,2) NOT NULL,
purchasing_power DECIMAL(5,2) NOT NULL,
safety DECIMAL(5,2) NOT NULL,
health_care DECIMAL(5,2) NOT NULL,
living_cost DECIMAL(5,2) NOT NULL,
prop_to_income_ratio DECIMAL(5,2) NOT NULL,
traffic DECIMAL(5,2) NOT NULL,
polution DECIMAL(5,2) NOT NULL,
climate DECIMAL(5,2) NOT NULL
);

CREATE TABLE `countries` (
id INTEGER NOT NULL PRIMARY KEY,
country VARCHAR(50) NOT NULL, 
score DECIMAL(5,2) NOT NULL,
gdp DECIMAL(5,2) NOT NULL,
social_support DECIMAL(5,2) NOT NULL,
life_expectancy DECIMAL(5,2) NOT NULL,
freedom DECIMAL(5,2) NOT NULL, 
generosity DECIMAL(5,2) NOT NULL, 
corruption DECIMAL(5,2) NOT NULL
);

CREATE TABLE `userCities` (
id INTEGER NOT NULL UNIQUE PRIMARY KEY,
city VARCHAR(50) NOT NULL,
happiness DECIMAL NOT NULL
);

CREATE TABLE `Users` (
id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
happiness DECIMAL,
position VARCHAR(150),
state VARCHAR(150),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

