CREATE DATABASE happiness;
USE happiness;

CREATE TABLE cities (
id INTEGER NOT NULL PRIMARY KEY, 
city VARCHAR(50) NOT NULL,
lifeQuality DECIMAL(5,2) NOT NULL,
purchasingPower DECIMAL(5,2) NOT NULL,
safety DECIMAL(5,2) NOT NULL,
healthCare DECIMAL(5,2) NOT NULL,
livingCost DECIMAL(5,2) NOT NULL,
propToIncomeRatio DECIMAL(5,2) NOT NULL,
traffic DECIMAL(5,2) NOT NULL,
polution DECIMAL(5,2) NOT NULL,
climate DECIMAL(5,2) NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE countries (
id INTEGER NOT NULL PRIMARY KEY,
country VARCHAR(50) NOT NULL, 
score DECIMAL(5,2) NOT NULL,
gdp DECIMAL(5,2) NOT NULL,
socialSupport DECIMAL(5,2) NOT NULL,
lifeExpectancy DECIMAL(5,2) NOT NULL,
freedom DECIMAL(5,2) NOT NULL, 
generosity DECIMAL(5,2) NOT NULL, 
corruption DECIMAL(5,2) NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE userCities (
id INTEGER NOT NULL UNIQUE PRIMARY KEY,
city VARCHAR(50) NOT NULL,
happiness DECIMAL NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Users (
id INTEGER NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) NOT NULL,
password VARCHAR(300) NOT NULL,
happiness DECIMAL,
position VARCHAR(150),
state VARCHAR(150),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

